{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.brscan.sdk",
    "module": "captura",
    "version": "1.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "captura-1.0.26.aar",
          "url": "captura-1.0.26.aar",
          "size": 649845,
          "sha512": "631feb0e9d9aaab61c554e4fe1ac172f62950799141d04f704a56bf1e333501711edde6d0e120d25af26e96649ea79243e945eaa2891b853d2ce09400eff99a6",
          "sha256": "d40af2ce0bc69f6c4173ae1c7147c42a64fe7d91d5f42ac624d41d03d7684f97",
          "sha1": "34bbac2de029530cb4b4f87bd94fbe9a10dbb3b7",
          "md5": "d3c218bf091b47241b8d59a37c35b3a9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.1-android"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "playstore-dynamic-feature-support",
          "version": {
            "requires": "16.0.0-beta1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "object-detection",
          "version": {
            "requires": "16.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.jsibbold",
          "module": "zoomage",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "captura-1.0.26.aar",
          "url": "captura-1.0.26.aar",
          "size": 649845,
          "sha512": "631feb0e9d9aaab61c554e4fe1ac172f62950799141d04f704a56bf1e333501711edde6d0e120d25af26e96649ea79243e945eaa2891b853d2ce09400eff99a6",
          "sha256": "d40af2ce0bc69f6c4173ae1c7147c42a64fe7d91d5f42ac624d41d03d7684f97",
          "sha1": "34bbac2de029530cb4b4f87bd94fbe9a10dbb3b7",
          "md5": "d3c218bf091b47241b8d59a37c35b3a9"
        }
      ]
    }
  ]
}
