{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.brscan.sdk.teste",
    "module": "teste",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "teste-1.0.0.aar",
          "url": "teste-1.0.0.aar",
          "size": 34768,
          "sha512": "24142325c2ad32fd8e3f2a1df6b229f7f027cc7b108f3a6fc8d6b0cf3bd305f5c91403a6f34f56d424404f7cd03925521b3a538b2eb83e2d97c01510980cf0b7",
          "sha256": "f61a9a07233f4cd1382689cddc86441433acc455efb013ffd7b36bf1e4522f9c",
          "sha1": "863b382cc1f7c7c4b99c2dbff26efc176f12263d",
          "md5": "fb7049d8c162809989b2f335b59458a6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "teste-1.0.0.aar",
          "url": "teste-1.0.0.aar",
          "size": 34768,
          "sha512": "24142325c2ad32fd8e3f2a1df6b229f7f027cc7b108f3a6fc8d6b0cf3bd305f5c91403a6f34f56d424404f7cd03925521b3a538b2eb83e2d97c01510980cf0b7",
          "sha256": "f61a9a07233f4cd1382689cddc86441433acc455efb013ffd7b36bf1e4522f9c",
          "sha1": "863b382cc1f7c7c4b99c2dbff26efc176f12263d",
          "md5": "fb7049d8c162809989b2f335b59458a6"
        }
      ]
    }
  ]
}
